-- ========================================================
-- Topic: Aggregating Data
-- DATABASE: dvdrental
-- ========================================================

-- 1. Count total number of payments and sum the revenue
SELECT 
    COUNT(*) AS total_transactions,
    SUM(amount) AS total_revenue
FROM payment;

-- 2. Group By: Find total revenue generated by each staff member
SELECT 
    staff_id,
    COUNT(payment_id) AS transactions_processed,
    SUM(amount) AS total_collected
FROM payment
GROUP BY staff_id;

-- 3. Group By Multiple Columns: Revenue per customer per staff member
SELECT 
    customer_id,
    staff_id,
    SUM(amount) AS total_spent
FROM payment
GROUP BY customer_id, staff_id
ORDER BY customer_id;
