-- ==========================================
-- PostgreSQL Identity Columns Practice Script
-- Target Database: 'trainings' (Empty database)
-- Use this script to test GENERATED ALWAYS vs GENERATED BY DEFAULT.
-- ==========================================

-- 1. Create table with GENERATED ALWAYS AS IDENTITY
DROP TABLE IF EXISTS identity_always_demo;

CREATE TABLE identity_always_demo (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    label TEXT NOT NULL
);

INSERT INTO identity_always_demo (label) VALUES ('Alpha'), ('Beta');
SELECT * FROM identity_always_demo;


-- 2. TEST MANUAL INSERT VIOLATION ON ALWAYS
-- Attempting manual insert on ALWAYS fails:
INSERT INTO identity_always_demo (id, label) VALUES (99, 'Gamma');
-- ERROR: cannot insert into column "id"

-- Override system value explicitly:
INSERT INTO identity_always_demo (id, label) OVERRIDING SYSTEM VALUE VALUES (99, 'Gamma');
SELECT * FROM identity_always_demo;


-- 3. Create table with GENERATED BY DEFAULT AS IDENTITY
DROP TABLE IF EXISTS identity_default_demo;

CREATE TABLE identity_default_demo (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label TEXT NOT NULL
);

-- Works with auto-generated ID:
INSERT INTO identity_default_demo (label) VALUES ('Item 1');

-- Works with manual ID:
INSERT INTO identity_default_demo (id, label) VALUES (500, 'Item 500');

SELECT * FROM identity_default_demo;
